### ISSUE TITLE
MALI build broken

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#603]
@gahansen , your commits yesterday broke the CALI and MALI builds (ALI interfaced to CISM and MPAS).  I fixed most of them except a logic error in Interface.cpp for MALI (see attached log file).  Could you or @mperego please look at it and fix it?  You can reproduce the error by setting -DENABLE_MPAS_INTERFACE=ON.  
[out.txt](https://github.com/SNLComputation/Albany/files/4841075/out.txt)

**Comment by mperego** [comment]
It should be fixed now.

**Comment by ikalash** [comment]
Thanks @mperego !  I’ll close the issue once the nightlies run clean.

**Comment by gahansen** [comment]
Sorry about that. I had not enabled -DENABLE_MPAS_INTERFACE=ON in my testing builds - I'll turn this on from now on.

**Comment by ikalash** [comment]
No problem @gahansen .  Seems Mauro's fix fixed the problem (though a lot of the nightlies are still broken due to other issues...).
